#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "digipad"
name = "Digipad"

description.en = "Create multimedia collaborative walls"
description.fr = "Créer des murs collaboratifs multimédias"

version = "1.2.2~ynh1"

maintainers = ["mrflos"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://digipad.app/"
demo = "https://digipad.app/"
admindoc = "https://codeberg.org/ladigitale/digipad/src/branch/master/README.md"
code = "https://codeberg.org/ladigitale/digipad"

[integration]
yunohost = '>= 11.2.27'
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "100M"
ram.build = "150M"
ram.runtime = "150M"

[install]

[install.domain]
type = "domain"

[install.path]
type = "path"
default = "/digipad"

[install.init_main_permission]
type = "group"
default = "visitors"

[resources]

[resources.sources]

[resources.sources.main]
url = "https://codeberg.org/ladigitale/digipad/archive/1.2.2.tar.gz"
sha256 = "2a43a112eec9a9f1c23c9815e01af85c525583d884f4837d7d8bff779fa33a5a"
autoupdate.strategy = "latest_forgejo_tag"

[resources.system_user]
allow_email = true

[resources.install_dir]

[resources.data_dir]

[resources.permissions]
main.url = "/"

[resources.ports]
