#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "digipad"
name = "Digipad"

description.en = "Create multimedia collaborative walls"
description.fr = "Créer des murs collaboratifs multimédias"

version = "1.3.1~ynh1"

maintainers = ["mrflos"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://digipad.app/"
demo = "https://digipad.app/"
admindoc = "https://codeberg.org/ladigitale/digipad/src/branch/master/README.md"
code = "https://codeberg.org/ladigitale/digipad"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap =  false
sso = false

disk = "800M"
ram.build = "500M"
ram.runtime = "150M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    help.en = "Password to access the administration page `/admin`"
    help.fr ="Mot de passe pour accéder à la page d'administration `/admin`"
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://codeberg.org/ladigitale/digipad/archive/1.3.1.tar.gz"
    sha256 = "5ea70f68a9c4a8d9117913236954941d6cea7bd2cb48260786c86231ae80272f"
    autoupdate.strategy = "latest_forgejo_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-contrib, redis-server"

    [resources.database]
    type = "postgresql"
